language: go
sudo: false
dist: trusty

go_import_path: github.com/go-python/gpython

os:
  - linux

env:
 - TAGS="-tags travis"

matrix:
 fast_finish: true
 allow_failures:
   - go: master
 include:
   - go: 1.13.x
     env:
       - TAGS="-tags travis"
       - COVERAGE="-cover"
   - go: 1.12.x
     env:
       - TAGS="-tags travis"
   - go: master
     env:
       - TAGS="-tags travis"
       - GO111MODULE=on

cache:
  directories:
    - $HOME/bin/python3.8

before_install:
  - ./bin/install-python.sh $HOME/bin/python3.8

script:
 - go install -v $TAGS ./...
 - PATH=$HOME/bin/python3.8/bin:$PATH GOARCH=386   go test $TAGS ./...
 - PATH=$HOME/bin/python3.8/bin:$PATH GOARCH=amd64 go run ./ci/run-tests.go -race $TAGS $COVERAGE
 - PATH=$HOME/bin/python3.8/bin:$PATH python3.8 py3test.py

after_success:
 - bash <(curl -s https://codecov.io/bash)
